name: pluto_grid_plus
description: PlutoGrid plus is a maintained version of PlutoGrid, PlutoGrid is a
    dataGrid that can be controlled by the keyboard on desktop and web. Of course,
    it works well on Android and IOS. (DataGrid, DataTable, Data Grid, Data Table,
    Sticky)
version: 8.4.4
homepage: https://pluto.weblaze.dev
repository: https://github.com/doonfrs/pluto_grid_plus

environment:
    sdk: ^3.0.0

dependencies:
    flutter:
        sdk: flutter
    intl: ^0.19.0
    rxdart: ^0.28.0
    collection: ^1.19.0

dev_dependencies:
    build_runner: ^2.4.7
    flutter_lints: ^5.0.0
    flutter_test:
        sdk: flutter
    mockito: ^5.4.3
